name: 'Setup Blender'
description: 'Downloads and installs Blender for use in GitHub Actions'
inputs:
  version:
    description: 'Blender version to install (e.g. 4.2 or 4.2.1)'
    required: true
  
runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    - name: Set version variables
      shell: ${{ runner.os == 'Windows' && 'pwsh' || 'bash' }}
      run: |
        uv pip install bs4
        uv run ${{ github.action_path }}/scripts/set_versions.py ${{ inputs.version }}
        uv run ${{ github.action_path }}/scripts/scrape_daily.py


    - name: Install Blender Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        if [ "${{ inputs.version }}" = "daily" ]; then
          wget -nv $BLEND_URL_LINUX_X64 -O ./blender.tar.xz
        else
          wget -nv https://download.blender.org/release/Blender${BLENDER_BASE_VERSION}/blender-${FULL_VERSION}-linux-x64.tar.xz -O ./blender.tar.xz
        fi
        mkdir -p ./blender
        tar -xf ./blender.tar.xz -C ./blender --strip-components=1
        echo "$GITHUB_WORKSPACE/blender" >> $GITHUB_PATH

    - name: Install Blender MacOS ARM
      if: runner.os == 'macOS'
      shell: bash
      run: |
        if [ "${{ inputs.version }}" = "daily" ]; then
          curl -L -o blender.dmg $BLEND_URL_MACOS_ARM64
        else
          curl -L -o blender.dmg https://download.blender.org/release/Blender${BLENDER_BASE_VERSION}/blender-${FULL_VERSION}-macos-arm64.dmg
        fi
        hdiutil attach blender.dmg
        cp -R /Volumes/Blender/Blender.app /Applications/
        hdiutil detach /Volumes/Blender
        echo "/Applications/Blender.app/Contents/MacOS" >> $GITHUB_PATH

    - name: Install Blender Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        if ("${{ inputs.version }}" -eq "daily") {
          Invoke-WebRequest -Uri $env:BLEND_URL_WINDOWS_X64 -OutFile "blender.zip"
        } else {
          Invoke-WebRequest -Uri "https://download.blender.org/release/Blender${env:BLENDER_BASE_VERSION}/blender-${env:FULL_VERSION}-windows-x64.zip" -OutFile "blender.zip"
        }
        Expand-Archive -Path "blender.zip" -DestinationPath "blender"
        echo "$env:GITHUB_WORKSPACE\blender\blender-${env:FULL_VERSION}-windows-x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append