name: 'Setup Blender'
description: 'Downloads and installs Blender for use in GitHub Actions'
inputs:
  version:
    description: 'Blender version to install (e.g. 4.2 or 4.2.1)'
    required: true
  
runs:
  using: 'composite'
  steps:
    - name: Install Blender Linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        BLENDER_BASE_VERSION=$(echo "${{ inputs.version }}" | cut -d'.' -f1,2)
        FULL_VERSION=$(echo "${{ inputs.version }}" | grep -q '^\d\+\.\d\+$' && echo "${{ inputs.version }}.0" || echo "${{ inputs.version }}")
        wget -nv https://download.blender.org/release/Blender${BLENDER_BASE_VERSION}/blender-${FULL_VERSION}-linux-x64.tar.xz -O ./blender.tar.xz
        mkdir -p ./blender
        tar -xf ./blender.tar.xz -C ./blender --strip-components=1
        echo "$GITHUB_WORKSPACE/blender" >> $GITHUB_PATH

    - name: Install Blender MacOS ARM
      if: runner.os == 'macOS'
      shell: bash
      run: |
        BLENDER_BASE_VERSION=$(echo "${{ inputs.version }}" | cut -d'.' -f1,2)
        FULL_VERSION=$(echo "${{ inputs.version }}" | grep -q '^\d\+\.\d\+$' && echo "${{ inputs.version }}.0" || echo "${{ inputs.version }}")
        curl -L -o blender.dmg https://download.blender.org/release/Blender${BLENDER_BASE_VERSION}/blender-${FULL_VERSION}-macos-arm64.dmg
        hdiutil attach blender.dmg
        cp -R /Volumes/Blender/Blender.app /Applications/
        hdiutil detach /Volumes/Blender
        echo "/Applications/Blender.app/Contents/MacOS" >> $GITHUB_PATH

    - name: Install Blender Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $BlenderBaseVersion = "${{ inputs.version }}" -replace '^(\d+\.\d+).*','$1'
        $FullVersion = if ("${{ inputs.version }}" -match '^\d+\.\d+$') { "${{ inputs.version }}.0" } else { "${{ inputs.version }}" }
        Invoke-WebRequest -Uri "https://download.blender.org/release/Blender${BlenderBaseVersion}/blender-${FullVersion}-windows-x64.zip" -OutFile "blender.zip"
        Expand-Archive -Path "blender.zip" -DestinationPath "blender"
        echo "$env:GITHUB_WORKSPACE\blender\blender-${FullVersion}-windows-x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append