name: Run Tests

on: 
    push:
      branches: ["main"]
    pull_request:
      branches: ["*"]
    schedule:
     - cron: '0 0 * * *'
        
    
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 4
            fail-fast: false
            matrix:
              version: ["daily", "4.2", "4.3", "4.4", "4.3.2", "4.1", "4.0.2"]
              os: [macos-14, "ubuntu-latest", "windows-latest"]
        steps:
            - uses: actions/checkout@v4
            - name: Install Blender
              uses: ./
              with:
                version: ${{ matrix.version }}
            - name: Run tests in Blender
              run: blender --version
